name: game_sphere_bd
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # printing: ^5.11.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  http: ^1.1.2
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.11
  flutter_sslcommerz: ^2.2.2-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0" 


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true


  
  assets:
   - assets/images/
 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
